//
//  NTAIOChat.NTAIOInputTextManager.h
//  Generated by STFX Header Dump v1.1
//  Source: unknown
//

#import <Foundation/Foundation.h>

@interface NTAIOChat.NTAIOInputTextManager : _TtCs12_SwiftObject

#pragma mark - Ivars

// { void viewController }

@end
