//
//  NTAIOChat.NTAIOInputBarSceneEventEngine.h
//  Generated by STFX Header Dump v1.1
//  Source: unknown
//

#import <Foundation/Foundation.h>

@interface NTAIOChat.NTAIOInputBarSceneEventEngine : _TtCs12_SwiftObject

#pragma mark - Ivars

// { void inputEvents }
// { void lock }

@end
