//
//  AIOLib.AIOInputMatchPlugin.h
//  Generated by STFX Header Dump v1.1
//  Source: unknown
//

#import <Foundation/Foundation.h>

@interface AIOLib.AIOInputMatchPlugin : _TtCs12_SwiftObject

#pragma mark - Ivars

// { void _host }
// { void context }
// { void disableParser }
// { void defaultNormalTextColor }
// { void defaultHightlightTextColor }
// { void matcherDict }

@end
