//
//  QQMsgSenderUtil.h
//  Generated by STFX Header Dump v1.1
//  Source: unknown
//

#import <Foundation/Foundation.h>

@interface QQMsgSenderUtil : NSObject <IQQMsgSenderUtilService>

#pragma mark - Properties

@property (readonly, strong) unsigned long long hash;
@property (readonly, strong) Class superclass;
@property (readonly, copy) NSString description;
@property (readonly, copy) NSString debugDescription;

#pragma mark - Class Methods

+ (double)getSendTime;
+ (BOOL)GetSyncCookiesOfCurAccount:(id)arg1 ResultLen:(id)arg2;
+ (void)AddTerminalType4FileAssistant:(id)arg1 SendingModel:(id)arg2;
+ (int)SendPbMsg:(id)arg1 SendingModel:(id)arg2 Licence:(id)arg3;

@end
