//
//  QQInputMaterialConfig.h
//  Generated by STFX Header Dump v1.1
//  Source: unknown
//

#import <Foundation/Foundation.h>

@interface QQInputMaterialConfig : NSObject <NSCoding>

#pragma mark - Properties

@property (nonatomic) BOOL useRecommendedSticker;
@property (nonatomic) long long maxMatchLength;

#pragma mark - Ivars

// { BOOL _useRecommendedSticker }
// { long long _maxMatchLength }

#pragma mark - Instance Methods

- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (BOOL)useRecommendedSticker;
- (void)setUseRecommendedSticker:(BOOL)arg1;
- (long long)maxMatchLength;
- (void)setMaxMatchLength:(long long)arg1;

@end
