//
//  MsgManager.AIOAsyncMsgSendTask.h
//  Generated by STFX Header Dump v1.1
//  Source: unknown
//

#import <Foundation/Foundation.h>

@interface MsgManager.AIOAsyncMsgSendTask : NSObject

#pragma mark - Properties

@property (readonly, nonatomic) long long msgUniqueId;
@property (nonatomic) double uploadLoadingDelay;

#pragma mark - Ivars

// { void _currentStage }
// { void p_currentStageValue }
// { void rwLock }
// { void peerContact }
// { void recordLock }
// { void _msgRecord }
// { void elementsLock }
// { void _sendingElements }
// { void msgAttributeInfos }
// { void lifeCycleDidEndClusure }
// { void cancelSet }
// { void isCancel }
// { long long msgUniqueId }
// { double uploadLoadingDelay }

#pragma mark - Instance Methods

- (long long)msgUniqueId;
- (double)uploadLoadingDelay;
- (void)setUploadLoadingDelay:(double)arg1;
- (void)dealloc;
- (id)init;
- (void).cxx_destruct;

@end
