//
//  QQMinAIOInputView.h
//  Generated by STFX Header Dump v1.1
//  Source: unknown
//

#import <Foundation/Foundation.h>

@interface QQMinAIOInputView : UIView

#pragma mark - Ivars

// { id _textView }
// { id _leftKeyVoiceTransBtn }
// { id _rightKeyEmojTransBtn }

#pragma mark - Instance Methods

- (void).cxx_destruct;

@end
