//
//  QQInputAccessoryView.h
//  Generated by STFX Header Dump v1.1
//  Source: unknown
//

#import <Foundation/Foundation.h>

@interface QQInputAccessoryView : UICollectionView

#pragma mark - Instance Methods

- (BOOL)isSupportRightDragToGoBack;
- (void)deselectAllItems;

#pragma mark - Class Methods

+ (id)defaultInputAccessoryView;

@end
