//
//  QQInputTextView.h
//  Generated by STFX Header Dump v1.1
//  Source: unknown
//

#import <Foundation/Foundation.h>

@interface QQInputTextView : QQMenuTextView <NSLayoutManagerDelegate>

#pragma mark - Properties

@property (retain, nonatomic) UILabel placeholderLabel;
@property (nonatomic) BOOL didFlashScrollIndicators;
@property (nonatomic) double lastCheckHasImageTime;
@property (copy, nonatomic) NSString placeholder;
@property (copy, nonatomic) UIColor placeholderColor;
@property (nonatomic) unsigned long long maxNumberOfLines;
@property (nonatomic) unsigned long long minNumberOfLines;
@property (readonly, nonatomic) unsigned long long numberOfLines;
@property (nonatomic) unsigned long long pastableMediaTypes;
@property (readonly, nonatomic) BOOL isExpanding;
@property (nonatomic) BOOL didNotResignFirstResponder;
@property (nonatomic) BOOL loupeVisible;
@property (nonatomic) BOOL typingSuggestionEnabled;
@property (strong) BOOL alwaysDisplayPlaceHolder;
@property (nonatomic) long long popMeunType;
@property (copy, nonatomic) id (^)(...) popMenuActionBlock;
@property (copy, nonatomic) id (^)(...) popMenuTogetherEditActionBlock;
@property (nonatomic) unsigned long long layoutStyle;
@property (nonatomic) BOOL cacheHasImageState;
@property (readonly, strong) unsigned long long hash;
@property (readonly, strong) Class superclass;
@property (readonly, copy) NSString description;
@property (readonly, copy) NSString debugDescription;

#pragma mark - Ivars

// { unsigned long long _numberOfLines }
// { BOOL _didNotResignFirstResponder }
// { BOOL _loupeVisible }
// { BOOL _alwaysDisplayPlaceHolder }
// { BOOL _cacheHasImageState }
// { BOOL _didFlashScrollIndicators }
// { id _placeholderLabel }
// { unsigned long long _maxNumberOfLines }
// { unsigned long long _minNumberOfLines }
// { unsigned long long _pastableMediaTypes }
// { long long _popMeunType }
// { id _popMenuActionBlock }
// { id _popMenuTogetherEditActionBlock }
// { unsigned long long _layoutStyle }
// { double _lastCheckHasImageTime }

#pragma mark - Instance Methods

- (void)clearText;
- (void)scrollToCaretPositonAnimated:(BOOL)arg1;
- (void)scrollToCaretPositonBottomAnimated:(BOOL)arg1;
- (void)insertNewLineBreak;
- (void)insertTextAtCaretRange:(id)arg1;
- (_NSRange)insertText:(id)arg1 inRange:(_NSRange)arg2;
- (id)wordAtCaretRange:(id)arg1;
- (id)wordAtRange:(_NSRange)arg1 rangeInText:(id)arg2;
- (id)initWithFrame:(CGRect)arg1 textContainer:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)commonInit;
- (CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (BOOL)becomeFirstResponder;
- (void)textViewMenuControllerWillShow:(id)arg1;
- (void)setPopMeunType:(long long)arg1;
- (BOOL)canBecomeFirstResponder;
- (void)inputModeDidChange:(id)arg1;
- (void)insertMenuPopSubItemWith:(long long)arg1;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)MenuWrap:(id)arg1;
- (void)pasteImage:(id)arg1;
- (void)didTouchExitFullScreenMenuItem:(id)arg1;
- (void)allScreenInput:(id)arg1;
- (void)togetherEditAction:(id)arg1;
- (id)placeholderLabel;
- (id)placeholder;
- (id)placeholderColor;
- (unsigned long long)numberOfLines;
- (unsigned long long)maxNumberOfLines;
- (BOOL)isTypingSuggestionEnabled;
- (id)pastedItem;
- (BOOL)isPasteboardItemSupported;
- (id)pasteboardContentType;
- (BOOL)pasteboardContentHasImageType;
- (void)asyncCheckPasteboardHasImage;
- (id)supportedMediaTypes;
- (BOOL)isExpanding;
- (BOOL)shouldHidePlaceholder;
- (CGRect)placeholderRectThatFits:(CGRect)arg1;
- (double)getAppropriateHeight;
- (void)setPlaceholder:(id)arg1;
- (void)setPlaceholderColor:(id)arg1;
- (void)setTypingSuggestionEnabled:(BOOL)arg1;
- (void)setSelectedRange:(_NSRange)arg1;
- (void)setSelectedTextRange:(id)arg1;
- (void)setText:(id)arg1;
- (void)setFont:(id)arg1;
- (void)setTextAlignment:(long long)arg1;
- (void)paste:(id)arg1;
- (void)flashScrollIndicatorsIfNeeded;
- (void)refreshFirstResponder;
- (void)refreshInputViews;
- (void)didBeginEditing:(id)arg1;
- (void)didBeginEditing;
- (void)didChangeText:(id)arg1;
- (void)didEndEditing:(id)arg1;
- (void)becomeAllScreenInput;
- (void)resignAllScreenInput;
- (void)dealloc;
- (BOOL)resignFirstResponder;
- (BOOL)layoutManager:(id)arg1 shouldSetLineFragmentRect:(id)arg2 lineFragmentUsedRect:(id)arg3 baselineOffset:(id)arg4 inTextContainer:(id)arg5 forGlyphRange:(_NSRange)arg6;
- (void)SetKeyboardAppearanceBeforeBecomeFirstResponder;
- (void)setPlaceholderLabel:(id)arg1;
- (void)setMaxNumberOfLines:(unsigned long long)arg1;
- (unsigned long long)minNumberOfLines;
- (void)setMinNumberOfLines:(unsigned long long)arg1;
- (unsigned long long)pastableMediaTypes;
- (void)setPastableMediaTypes:(unsigned long long)arg1;
- (BOOL)didNotResignFirstResponder;
- (void)setDidNotResignFirstResponder:(BOOL)arg1;
- (BOOL)isLoupeVisible;
- (void)setLoupeVisible:(BOOL)arg1;
- (BOOL)alwaysDisplayPlaceHolder;
- (void)setAlwaysDisplayPlaceHolder:(BOOL)arg1;
- (long long)popMeunType;
- (id)popMenuActionBlock;
- (void)setPopMenuActionBlock:(id)arg1;
- (id)popMenuTogetherEditActionBlock;
- (void)setPopMenuTogetherEditActionBlock:(id)arg1;
- (unsigned long long)layoutStyle;
- (void)setLayoutStyle:(unsigned long long)arg1;
- (BOOL)cacheHasImageState;
- (void)setCacheHasImageState:(BOOL)arg1;
- (BOOL)didFlashScrollIndicators;
- (void)setDidFlashScrollIndicators:(BOOL)arg1;
- (double)lastCheckHasImageTime;
- (void)setLastCheckHasImageTime:(double)arg1;
- (void).cxx_destruct;

#pragma mark - Class Methods

+ (BOOL)requiresConstraintBasedLayout;

@end
