//
//  QQInputBgView.h
//  Generated by STFX Header Dump v1.1
//  Source: unknown
//

#import <Foundation/Foundation.h>

@interface QQInputBgView : UIImageView

#pragma mark - Properties

@property (retain, nonatomic) UIImage bgImage;

#pragma mark - Ivars

// { id _bgImage }

#pragma mark - Instance Methods

- (void)setSkinImageNormal:(id)arg1;
- (void)setBgImage:(id)arg1;
- (id)bgImage;
- (void).cxx_destruct;

@end
