//
//  NTAIOChat.NTAIOShortcutBarItemInputBarViewController.h
//  Generated by STFX Header Dump v1.1
//  Source: unknown
//

#import <Foundation/Foundation.h>

@interface NTAIOChat.NTAIOShortcutBarItemInputBarViewController : AIOLib.AIOShortBarItemBaseViewController <AIOLib.AIOBaseDTReportProtocol, INTAIOChatProtocol.IFaceRecommenCellTapProtocol, AIOLib.AIOClassicEmojiNotifyProtocol, AIOLib.AIORichBoardContainerNotifyProtocol, AIOLib.AIOTableViewClickActionProtocol, AIOLib.AIOShortcutBarItemViewDelegate>

#pragma mark - Ivars

// { void inputBarContentObserver }
// { void inputBarTextReplacementObserver }
// { void inputBarTextLimitLength }
// { void inputBarTextByteLimitLength }
// { void inputBarTextRate }
// { void inputBarCurrentText }
// { void _isContainDraft }
// { void custumCheckTextLengthBlock }
// { void inputBarView }
// { void inputBarAllScreenViewModel }
// { void textEffectViewModel }
// { void hasLimitCount }
// { void sceneCoordinator }
// { void kAioInputActionSwitch }
// { void isInputActionSwitchOn }
// { void feedbackGenerator }
// { void $__lazy_storage_$_audioInputEntrance }
// { void needShowEssenceBtn }
// { void menuExposeTime }

#pragma mark - Instance Methods

- (void)dtReportInputFullScreenBtnClick;
- (void)dtReportInputFullScreenBtnExpose;
- (void)dtReportInputFullScreenBtnExposeEnd;
- (void)dtReportInputPressMenuExpose;
- (void)dtReportInputPressMenuExposeEnd;
- (void)dtReportInputPressMenuClick:(id)arg1;
- (void)checkTextForFaceRecommendationWithOnwerVC:(id)arg1 text:(id)arg2;
- (void)didTapCell;
- (void)inputBarAddWithText:(id)arg1 becomeFirstResponder:(BOOL)arg2;
- (void)callInputBarWithUid:(id)arg1 uin:(id)arg2 sendName:(id)arg3 attached:(id)arg4;
- (void)actionDelete;
- (void)actionSend;
- (void)allScreenInputWithSender:(id)arg1;
- (void)clearInputBarContent:(id)arg1;
- (void)didTriggerLongPressedByLongPressGesture:(id)arg1;
- (void)handleMenuHidden:(id)arg1;
- (void)handleMenuShown:(id)arg1;
- (void)handleMunuWrapAction:(id)arg1;
- (void)handleResignFullScreenState:(id)arg1;
- (void)itemViewSizeDidChange:(id)arg1;
- (void)richBoardDidClosed:(id)arg1;
- (void)richBoardDidShow:(id)arg1;
- (void)richBoardWillClosed:(id)arg1;
- (void)richBoardWillShow:(id)arg1;
- (void)showAllScreenOutsideView:(BOOL)arg1;
- (void)tableView:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (void)didTap;
- (void)viewDidLayoutSubviews;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end
