//
//  QQInputTextViewController.h
//  Generated by STFX Header Dump v1.1
//  Source: unknown
//

#import <Foundation/Foundation.h>

@interface QQInputTextViewController : QQViewController <QQFaceEmojiPanelStretchDelegate, UITextViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UIGestureRecognizerDelegate, UIAlertViewDelegate>

#pragma mark - Properties

@property (strong) BOOL registKVO;
@property (retain) NSMutableDictionary customTableViewOffsetYLayers;
@property (weak, nonatomic) UIScrollView scrollViewProxy;
@property (retain, nonatomic) QQInputbar inputbar;
@property (retain, nonatomic) NSLayoutConstraint scrollViewHC;
@property (retain, nonatomic) NSLayoutConstraint scrollViewTopC;
@property (retain, nonatomic) NSLayoutConstraint scrollViewBottomC;
@property (retain, nonatomic) NSLayoutConstraint inputbarHC;
@property (retain, nonatomic) NSLayoutConstraint keyboardHC;
@property (retain, nonatomic) NSLayoutConstraint inputBgViewHC;
@property (retain, nonatomic) NSLayoutConstraint inputPanelViewHC;
@property (retain, nonatomic) NSLayoutConstraint inputPanelViewBottomC;
@property (copy, nonatomic) id (^)(...) sklInputViewAniamtionCompletion;
@property (nonatomic) unsigned long long keyboardStatus;
@property (nonatomic) BOOL viewVisible;
@property (nonatomic) BOOL animationEnable;
@property (nonatomic) BOOL rotating;
@property (retain, nonatomic) Class textViewClass;
@property (nonatomic) long long debugDog;
@property (nonatomic) unsigned long long isAtViewWillAppearStageFlag;
@property (nonatomic) double kbHeightBeforePan;
@property (nonatomic) CGPoint prevTranslation;
@property (nonatomic) long long inputPanelState;
@property (nonatomic) long long inputbarPanDirection;
@property (readonly, nonatomic) UITableView tableView;
@property (nonatomic) UIEdgeInsets defaultScrollViewContentInset;
@property (retain, nonatomic) NSArray inputbarItems;
@property (nonatomic) BOOL isInputPanelViewVisible;
@property (retain, nonatomic) QQInputPanelView inputPanelView;
@property (readonly, nonatomic) CGRect inputPanelDefaultBounds;
@property (retain, nonatomic) QQInputBgView inputBgView;
@property (readonly, nonatomic) UIGestureRecognizer singleTapGesture;
@property (readonly, nonatomic) UIPanGestureRecognizer verticalPanGesture;
@property (nonatomic) BOOL keyboardPanningEnabled;
@property (nonatomic) BOOL shouldScrollToBottomAfterKeyboardShows;
@property (readonly, nonatomic) QQInputDefaultTextView aioTextView;
@property (readonly, nonatomic) UIView aioVoiceInputView;
@property (nonatomic) double scrollViewBottomMargin;
@property (nonatomic) double scrollViewTopMargin;
@property (nonatomic) double scrollViewTapHeadMargin;
@property (nonatomic) double inputBarAllScreenHeight;
@property (nonatomic) BOOL inputbarHidden;
@property (readonly, nonatomic) BOOL inputBarPresented;
@property (retain, nonatomic) UIView containertView;
@property (readonly, nonatomic) double customTableViewOffsetY;
@property (nonatomic) long long defaultIndexForSelectedInputbarItem;
@property (nonatomic) BOOL isTextEffectEditing;
@property (readonly, strong) unsigned long long hash;
@property (readonly, strong) Class superclass;
@property (readonly, copy) NSString description;
@property (readonly, copy) NSString debugDescription;

#pragma mark - Ivars

// { BOOL _isInputPanelViewInDismissAnimation }
// { BOOL _isInputPanelViewVisible }
// { BOOL _keyboardPanningEnabled }
// { BOOL _shouldScrollToBottomAfterKeyboardShows }
// { BOOL _inputbarHidden }
// { BOOL _isTextEffectEditing }
// { BOOL _registKVO }
// { BOOL _viewVisible }
// { BOOL _animationEnable }
// { BOOL _rotating }
// { id _tableView }
// { id _inputbar }
// { id _inputbarItems }
// { id _inputPanelView }
// { id _inputBgView }
// { id _singleTapGesture }
// { id _verticalPanGesture }
// { double _scrollViewBottomMargin }
// { double _scrollViewTopMargin }
// { double _scrollViewTapHeadMargin }
// { double _inputBarAllScreenHeight }
// { id _containertView }
// { double _customTableViewOffsetY }
// { long long _defaultIndexForSelectedInputbarItem }
// { id _customTableViewOffsetYLayers }
// { id _scrollViewProxy }
// { id _scrollViewHC }
// { id _scrollViewTopC }
// { id _scrollViewBottomC }
// { id _inputbarHC }
// { id _keyboardHC }
// { id _inputBgViewHC }
// { id _inputPanelViewHC }
// { id _inputPanelViewBottomC }
// { id _sklInputViewAniamtionCompletion }
// { unsigned long long _keyboardStatus }
// { Class _textViewClass }
// { long long _debugDog }
// { unsigned long long _isAtViewWillAppearStageFlag }
// { double _kbHeightBeforePan }
// { long long _inputPanelState }
// { long long _inputbarPanDirection }
// { CGPoint _prevTranslation }
// { UIEdgeInsets _defaultScrollViewContentInset }

#pragma mark - Instance Methods

- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithTableView:(id)arg1;
- (void)commonInit;
- (void)changeStatusBarFrame:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)setCustomTableViewOffsetY:(double)arg1 forLayerKey:(id)arg2;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillLayoutSubviews;
- (BOOL)isSupportFullScreenLayout;
- (id)inputbar;
- (id)createInputBar;
- (id)inputPanelView;
- (id)inputBgView;
- (CGRect)inputPanelDefaultBounds;
- (id)aioTextView;
- (id)aioVoiceInputView;
- (double)appropriateKeyboardHeightFromNotification:(id)arg1;
- (double)scaleAIOBottomSpace;
- (double)homeIndicatorHeight;
- (double)appropriateInputPanelViewHeight;
- (double)appropriateScrollViewBottomMargin;
- (double)keyboardTopMargin;
- (void)adjustScrollViewContentInset;
- (void)adjustScrollViewContentInset:(int)arg1;
- (UIEdgeInsets)defaultScrollViewInset;
- (void)inputBarFrameChangeAnimation:(BOOL)arg1;
- (double)minimumInputbarHeight;
- (id)appropriateKeyboardNotificationName:(id)arg1;
- (unsigned long long)keyboardStatusForNotification:(id)arg1;
- (BOOL)isIllogicalKeyboardStatus:(unsigned long long)arg1;
- (void)setDefaultScrollViewContentInset:(UIEdgeInsets)arg1;
- (void)setScrollViewProxy:(id)arg1;
- (BOOL)updateKeyboardStatus:(unsigned long long)arg1;
- (void)setInputbarItems:(id)arg1;
- (void)setInputbarItemsWithoutReloadData:(id)arg1;
- (void)updateScrollViewTopBottmConstraints:(double)arg1 topC:(double)arg2 curTopC:(id)arg3 curBottomC:(id)arg4;
- (void)setInputbarHidden:(BOOL)arg1;
- (void)setInputbarHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (BOOL)isInputBarPresented;
- (BOOL)shouldPresentKeyboardWhenViewWillAppear;
- (void)showAIOVoiceInputView;
- (void)hiddenAIOVoiceInputView;
- (BOOL)ableToShowVoiceInputView;
- (void)presentKeyboard:(BOOL)arg1;
- (void)dismissKeyboard:(BOOL)arg1;
- (BOOL)ignoreInputbarAdjustment;
- (void)didChangeKeyboardStatus:(unsigned long long)arg1;
- (void)willChangeInputbarStatus:(unsigned long long)arg1;
- (void)textWillUpdate;
- (void)willChangeInputPannelStatus:(BOOL)arg1;
- (void)textDidUpdate:(BOOL)arg1;
- (void)textSelectionDidChange;
- (void)didPasteMediaContent:(id)arg1;
- (BOOL)isInputPanelViewVisible;
- (void)presentInputPanelView:(BOOL)arg1;
- (void)presentInputPanelView:(BOOL)arg1 force:(BOOL)arg2;
- (void)presentInputPanelView:(BOOL)arg1 force:(BOOL)arg2 completion:(id)arg3;
- (void)dismissInputPanelView:(BOOL)arg1;
- (void)dismissInputPanelView:(BOOL)arg1 force:(BOOL)arg2;
- (void)dismissKeyboardAndInputPanelView:(BOOL)arg1;
- (void)forceToUpdateConstraints;
- (void)hiddenInputBGViewIfNeed;
- (void)didTapScrollView:(id)arg1;
- (void)didPanTextView:(id)arg1;
- (void)postKeyboarStatusNotification:(id)arg1;
- (BOOL)scrollToTopIfNeeded;
- (BOOL)shouldShowSubPopView;
- (BOOL)scrollToBottomIfNeeded;
- (void)enableTypingSuggestionIfNeeded;
- (BOOL)canSupportConciseAllScreenInput;
- (void)becomeAllScreenInputRestoreLayout:(BOOL)arg1;
- (BOOL)becomeAllScreenInputStatus;
- (void)resignAllScreenInputRestoreLayout:(BOOL)arg1;
- (BOOL)resignAllScreenInputStatus;
- (void)willShowOrHideKeyboardAnimation:(id)arg1 status:(unsigned long long)arg2;
- (BOOL)willShowOrHideKeyboardStatusCheck:(id)arg1;
- (void)willShowOrHideKeyboardCSShowChanage:(id)arg1;
- (void)willShowOrHideKeyboardUpdateKeyboardHC:(id)arg1;
- (void)willShowOrHideKeyboard:(id)arg1;
- (void)didShowOrHideKeyboard:(id)arg1;
- (void)didKeyboardChangeFrame:(id)arg1;
- (void)didPostQQKeyboardNotification:(id)arg1;
- (void)willChangeTextViewText:(id)arg1;
- (void)didChangeTextViewText:(id)arg1;
- (void)didChangeTextViewContentSize:(id)arg1;
- (void)didChangeTextViewSelectedRange:(id)arg1;
- (void)didChangeTextViewPasteboard:(id)arg1;
- (id)keyForSelectedInputbarItemCaching;
- (long long)indexOfCachedSelectedInputbarItem;
- (void)cacheSelectedInputbarItem;
- (void)clearCachedSelectedInputbarItem;
- (void)registerClassForTextView:(Class)arg1;
- (BOOL)textViewShouldBeginEditing:(id)arg1;
- (void)shouldChangeTextInRangeReport;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(_NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (BOOL)scrollViewShouldScrollToTop:(id)arg1;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldDeselectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)setupViewConstraints;
- (void)updateInputPanelView:(CGRect)arg1 inputView:(CGRect)arg2;
- (void)updateScrollViewConstraints;
- (void)registerNotifications;
- (void)unregisterNotifications;
- (void)registerKVO;
- (void)unregisterKVO;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(id)arg4;
- (void)didSelectInputbarItemAtIndexPath:(id)arg1;
- (BOOL)shouldPresentInputPanelView:(id)arg1;
- (void)selectInputbarItemAtIndex:(unsigned long long)arg1;
- (void)deselectAllInputbarItems;
- (id)indexPathForSelectedInputbarItem;
- (void)didPressLeftLButton:(id)arg1;
- (void)didPressLeftRButton:(id)arg1;
- (void)didPressRightLButton:(id)arg1;
- (void)didPressRightRButton:(id)arg1;
- (void)didPressRightMButton:(id)arg1;
- (void)didPressTextEffectButton:(id)arg1;
- (void)didPressAioVoiceInputViewLongPress:(id)arg1;
- (void)dealloc;
- (BOOL)shouldRecognizePan;
- (void)inputbarPanCancelledOrEnded;
- (void)inputbarPan:(id)arg1;
- (BOOL)isNormalInputPanel;
- (BOOL)isMaxInputPanel;
- (void)normalizeInputPanel:(BOOL)arg1;
- (void)normalizeInputPanel:(BOOL)arg1 completion:(id)arg2;
- (double)inputPanelMaxHeight;
- (void)maximizeInputPanel;
- (void)maximizeInputPanel:(BOOL)arg1 completion:(id)arg2;
- (void)maximizeInputPanelWithCompletion:(id)arg1;
- (void)makeInputBgViewAdjustTheme;
- (BOOL)needSupportBottomSafeAearInset;
- (id)getContainertView;
- (BOOL)isAIOInputEntryConfigurable;
- (BOOL)isHitConsiceFacePanelExp;
- (id)tableView;
- (UIEdgeInsets)defaultScrollViewContentInset;
- (void)setInputbar:(id)arg1;
- (id)inputbarItems;
- (void)setIsInputPanelViewVisible:(BOOL)arg1;
- (void)setInputPanelView:(id)arg1;
- (void)setInputBgView:(id)arg1;
- (id)singleTapGesture;
- (id)verticalPanGesture;
- (BOOL)isKeyboardPanningEnabled;
- (void)setKeyboardPanningEnabled:(BOOL)arg1;
- (BOOL)shouldScrollToBottomAfterKeyboardShows;
- (void)setShouldScrollToBottomAfterKeyboardShows:(BOOL)arg1;
- (double)scrollViewBottomMargin;
- (void)setScrollViewBottomMargin:(double)arg1;
- (double)scrollViewTopMargin;
- (void)setScrollViewTopMargin:(double)arg1;
- (double)scrollViewTapHeadMargin;
- (void)setScrollViewTapHeadMargin:(double)arg1;
- (double)inputBarAllScreenHeight;
- (void)setInputBarAllScreenHeight:(double)arg1;
- (BOOL)isInputbarHidden;
- (id)containertView;
- (void)setContainertView:(id)arg1;
- (double)customTableViewOffsetY;
- (long long)defaultIndexForSelectedInputbarItem;
- (void)setDefaultIndexForSelectedInputbarItem:(long long)arg1;
- (BOOL)isTextEffectEditing;
- (void)setIsTextEffectEditing:(BOOL)arg1;
- (BOOL)registKVO;
- (void)setRegistKVO:(BOOL)arg1;
- (id)customTableViewOffsetYLayers;
- (void)setCustomTableViewOffsetYLayers:(id)arg1;
- (id)scrollViewProxy;
- (id)scrollViewHC;
- (void)setScrollViewHC:(id)arg1;
- (id)scrollViewTopC;
- (void)setScrollViewTopC:(id)arg1;
- (id)scrollViewBottomC;
- (void)setScrollViewBottomC:(id)arg1;
- (id)inputbarHC;
- (void)setInputbarHC:(id)arg1;
- (id)keyboardHC;
- (void)setKeyboardHC:(id)arg1;
- (id)inputBgViewHC;
- (void)setInputBgViewHC:(id)arg1;
- (id)inputPanelViewHC;
- (void)setInputPanelViewHC:(id)arg1;
- (id)inputPanelViewBottomC;
- (void)setInputPanelViewBottomC:(id)arg1;
- (id)sklInputViewAniamtionCompletion;
- (void)setSklInputViewAniamtionCompletion:(id)arg1;
- (unsigned long long)keyboardStatus;
- (void)setKeyboardStatus:(unsigned long long)arg1;
- (BOOL)isViewVisible;
- (void)setViewVisible:(BOOL)arg1;
- (BOOL)animationEnable;
- (void)setAnimationEnable:(BOOL)arg1;
- (BOOL)isRotating;
- (void)setRotating:(BOOL)arg1;
- (Class)textViewClass;
- (void)setTextViewClass:(Class)arg1;
- (long long)debugDog;
- (void)setDebugDog:(long long)arg1;
- (unsigned long long)isAtViewWillAppearStageFlag;
- (void)setIsAtViewWillAppearStageFlag:(unsigned long long)arg1;
- (double)kbHeightBeforePan;
- (void)setKbHeightBeforePan:(double)arg1;
- (CGPoint)prevTranslation;
- (void)setPrevTranslation:(CGPoint)arg1;
- (long long)inputPanelState;
- (void)setInputPanelState:(long long)arg1;
- (long long)inputbarPanDirection;
- (void)setInputbarPanDirection:(long long)arg1;
- (void).cxx_destruct;

@end
